name: doctor_ki_bole_app
description: A Bangla medical AI assistant powered by ChatGPT

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  shared_preferences: ^2.2.2
  speech_to_text: ^6.3.0
  pdf_text: ^1.0.0
  camera: ^0.10.5+1
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.10.0
